tasks:
- name: Terminal
  init: >
    echo "Compilando la aplicación:";
    javac Pruebas.java;
    echo "Ejecutando la aplicación:";
    echo -e "5\n5" | java Pruebas
  command: >
    echo "";
    echo "Recuerda que pudes hacer:";
    echo " * javac Pruebas.java";
    echo ' * echo -e "5\n5" | java Pruebas'